import streamlit as st
import pandas as pd
import time

st.set_page_config(page_title="SIH Traffic AI", layout="wide")

st.title("🚦 Smart Traffic Management System (SIH1607)")
st.markdown("Real-time monitoring of adaptive traffic signals.")

# Layout
col1, col2 = st.columns(2)
placeholder = st.empty()

while True:
    try:
        # Read the live data generated by main.py
        df = pd.read_csv("live_data.csv")
        
        if not df.empty:
            last_row = df.iloc[-1]
            current_cars = int(last_row["waiting_cars"])
            status = last_row["status"]
            
            with placeholder.container():
                # Metrics
                kpi1, kpi2, kpi3 = st.columns(3)
                kpi1.metric("Simulation Step", int(last_row["step"]))
                kpi2.metric("Waiting Vehicles", current_cars, delta_color="inverse")
                
                # Dynamic Alert Box
                if current_cars > 10:
                    kpi3.error(f"🚨 {status}")
                else:
                    kpi3.success(f"✅ {status}")

                # Live Chart
                st.subheader("Traffic Density Trend")
                st.line_chart(df.set_index("step")["waiting_cars"])

        time.sleep(1) # Refresh every second
        
    except FileNotFoundError:
        st.warning("Waiting for simulation to start...")
        time.sleep(2)